version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app

      #Uvicorn을 --reload옵션과 함께 실행하여 파일 변경시 자동재시작
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
